AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/delayed_job'
    - 'app/views/posts/*.haml'
    - 'app/views/**/*.haml'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
Documentation:
  Enabled: false

# Block Length rule (max 25 lines in block) should not apply to declarative
# pieces of code such as specs
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'test/**/*.rb'
    - 'spec/features/*.rb'
